# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(838, 587)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tab = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tab.setFont(font)
        self.tab.setObjectName("tab")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.w1 = ImageView(self.tab1)
        self.w1.setObjectName("w1")
        self.horizontalLayout.addWidget(self.w1)
        self.w2 = ImageView(self.tab1)
        self.w2.setObjectName("w2")
        self.horizontalLayout.addWidget(self.w2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.b1 = QtWidgets.QPushButton(self.tab1)
        self.b1.setObjectName("b1")
        self.horizontalLayout_2.addWidget(self.b1)
        self.b2 = QtWidgets.QPushButton(self.tab1)
        self.b2.setObjectName("b2")
        self.horizontalLayout_2.addWidget(self.b2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tab.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.b3 = QtWidgets.QPushButton(self.tab2)
        self.b3.setObjectName("b3")
        self.horizontalLayout_3.addWidget(self.b3)
        self.b4 = QtWidgets.QPushButton(self.tab2)
        self.b4.setObjectName("b4")
        self.horizontalLayout_3.addWidget(self.b4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.tab2)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.w3 = ImageView(self.tab2)
        self.w3.setObjectName("w3")
        self.horizontalLayout_4.addWidget(self.w3)
        self.w4 = ImageView(self.tab2)
        self.w4.setObjectName("w4")
        self.horizontalLayout_4.addWidget(self.w4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.w5 = ImageView(self.tab2)
        self.w5.setObjectName("w5")
        self.horizontalLayout_5.addWidget(self.w5)
        self.w6 = ImageView(self.tab2)
        self.w6.setObjectName("w6")
        self.horizontalLayout_5.addWidget(self.w6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.b5 = QtWidgets.QPushButton(self.tab2)
        self.b5.setObjectName("b5")
        self.verticalLayout_3.addWidget(self.b5)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tab.addTab(self.tab2, "")
        self.gridLayout_4.addWidget(self.tab, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.w1.ui.histogram.hide()
        self.w1.ui.roiBtn.hide()
        self.w1.ui.menuBtn.hide()
        self.w1.ui.roiPlot.hide()
        self.w2.ui.histogram.hide()
        self.w2.ui.roiBtn.hide()
        self.w2.ui.menuBtn.hide()
        self.w2.ui.roiPlot.hide()
        self.w3.ui.histogram.hide()
        self.w3.ui.roiBtn.hide()
        self.w3.ui.menuBtn.hide()
        self.w3.ui.roiPlot.hide()
        self.w4.ui.histogram.hide()
        self.w4.ui.roiBtn.hide()
        self.w4.ui.menuBtn.hide()
        self.w4.ui.roiPlot.hide()
        self.w5.ui.histogram.hide()
        self.w5.ui.roiBtn.hide()
        self.w5.ui.menuBtn.hide()
        self.w5.ui.roiPlot.hide()
        self.w6.ui.histogram.hide()
        self.w6.ui.roiBtn.hide()
        self.w6.ui.menuBtn.hide()
        self.w6.ui.roiPlot.hide()
        self.retranslateUi(MainWindow)
        self.tab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Matching Templates"))
        self.b1.setText(_translate("MainWindow", "Import Image"))
        self.b2.setText(_translate("MainWindow", "Show Harris Points"))
        self.tab.setTabText(self.tab.indexOf(self.tab1), _translate("MainWindow", "Harris Operator"))
        self.b3.setText(_translate("MainWindow", "Import Image"))
        self.b4.setText(_translate("MainWindow", "Import Template"))
        self.label.setText(_translate("MainWindow", "Matching with SSD"))
        self.label_2.setText(_translate("MainWindow", "Matching with Normalized Cross Correlation"))
        self.b5.setText(_translate("MainWindow", "Apply SIFT and Matching"))
        self.tab.setTabText(self.tab.indexOf(self.tab2), _translate("MainWindow", "SIFT and Matching"))
from pyqtgraph import ImageView


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
